site_name: Hardening Framework
site_description: DevOps and Security
theme: readthedocs
docs_dir: docs
repo_url: https://github.com/hardening-io/docs
pages:

# Introduction
- ['index.md', 'Introduction']

# Coding
- ['coding/contributing.md', 'Coding', 'Contributing']
- ['coding/linting.md', 'Coding', 'Linting']
- ['coding/headers.md', 'Coding', 'File headers']

# Principles
- ['principles.md', 'Principles']

# Chef
- ['chef.md', 'Chef']

# Puppet
- ['puppet.md', 'Puppet']

# Faq
- ['faq.md', 'FAQ']